# Generated by Django 5.1.4 on 2025-01-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_postmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
