# Generated by Django 5.1.4 on 2025-01-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='Core.hashtag'),
        ),
    ]
