# Generated by Django 5.1.4 on 2025-01-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
